#pragma once

namespace NetworkShared {
	enum ServerPacket {
		LINK_RESPONSE = 0,
		GAME_INFO = 1,
		PLAYERS_INFO = 2,
		SET_PHASE = 15,
		UPDATE_PLAYER_HEALTH = 19,
		UPDATE_PLAYER_MOVEMENT = 16,
		TP_PLAYER = 21,
		ENTITIES_INFO = 22,
		UPDATE_ENTITY = 23,
		CHAT_MESSAGE = 31
	};

	enum ClientPacket {
		LINK_KEY = 0,
		UPDATE_MOVEMENT = 16,
		ACTION_GRAB = 17,
		ACTION_DROP = 18,
		ACTION_USE = 19,
		ACTION_TAKE_DAMAGE = 20,
		ACTION_CHAT_MESSAGE = 31
	};


}
